import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { execFileSync } from "node:child_process";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const PAPER = path.join(ROOT, "paper", "main.tex");
const BUILD = path.join(ROOT, "scripts", ".tables-build");
const OUT = path.join(ROOT, "public", "figures", "tables");

// ---------- helpers ----------
function readBalanced(text, openIdx) {
  // openIdx points at the opening '{'
  let depth = 0;
  for (let i = openIdx; i < text.length; i++) {
    if (text[i] === "{") depth++;
    else if (text[i] === "}") {
      depth--;
      if (depth === 0) return text.slice(openIdx + 1, i);
    }
  }
  return "";
}

function latexCaptionToHtml(s) {
  return s
    .replace(/\\textbf\{([^}]*)\}/g, "<b>$1</b>")
    .replace(/\\emph\{([^}]*)\}/g, "<em>$1</em>")
    .replace(/\\texttt\{([^}]*)\}/g, "<code>$1</code>")
    .replace(/\\&/g, "&")
    .replace(/\\%/g, "%")
    .replace(/\\_/g, "_")
    .replace(/\\\$/g, "$")
    .replace(/\\\{/g, "{")
    .replace(/\\\}/g, "}")
    .replace(/~/g, " ")
    .replace(/\\\\/g, " ")
    .replace(/\\[a-zA-Z]+/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

function sanitizeTableBody(s) {
  return s
    .replace(/\\includegraphics(?:\[[^\]]*\])?\{[^}]*\}/g, "") // drop images
    .replace(/\\cite\{([^}]*)\}/g, "[$1]") // keep citation keys as text
    .replace(/\\ref\{([^}]*)\}/g, "?") // dangling refs -> ?
    .replace(/\\label\{([^}]*)\}/g, ""); // drop labels
}

// ---------- read paper ----------
const tex = fs.readFileSync(PAPER, "utf8");
const docBegin = tex.indexOf("\\begin{document}");
const titleIdx = tex.indexOf("\\title{");
const preamble = tex.slice(0, docBegin); // lines 1..157
const prelude = tex.slice(docBegin + "\\begin{document}".length, titleIdx); // macro/color defs in body

// ---------- extract active table* blocks ----------
const tables = [];
const lines = tex.split("\n");
let i = 0;
while (i < lines.length) {
  const trimmed = lines[i].trim();
  const m = trimmed.match(/^\\begin\{table\*?\}\s*\[/);
  if (m && !trimmed.startsWith("%")) {
    // collect until matching \end{table*}
    let buf = lines[i] + "\n";
    let depth = 0;
    // count opens from this line
    const openHere = (lines[i].match(/\\begin\{table\*?\}/g) || []).length;
    depth += openHere;
    let j = i + 1;
    while (j < lines.length && depth > 0) {
      const l = lines[j];
      depth += (l.match(/\\begin\{table\*?\}/g) || []).length;
      depth -= (l.match(/\\end\{table\*?\}/g) || []).length;
      buf += l + "\n";
      j++;
    }
    const body = sanitizeTableBody(buf);
    const capIdx = body.indexOf("\\caption{");
    const captionRaw = capIdx >= 0 ? readBalanced(body, capIdx + 8) : "";
    tables.push({ body, caption: latexCaptionToHtml(captionRaw) });
    i = j;
  } else {
    i++;
  }
}

if (tables.length === 0) {
  console.log("No active tables found.");
  process.exit(0);
}
console.log(`Found ${tables.length} active tables.\n`);

fs.mkdirSync(BUILD, { recursive: true });
fs.mkdirSync(OUT, { recursive: true });

const manifest = [];

tables.forEach((t, idx) => {
  const n = idx + 1;
  const base = `table${n}`;
  const texPath = path.join(BUILD, `${base}.tex`);
  const pdfPath = path.join(BUILD, `${base}.pdf`);
  const pngPath = path.join(OUT, `${base}.png`);

  const standalone = `${preamble}\n\\begin{document}\n${prelude}\n${t.body}\n\\end{document}\n`;
  fs.writeFileSync(texPath, standalone);

  try {
    execFileSync(
      "pdflatex",
      ["-interaction=nonstopmode", "-halt-on-error", `-output-directory=${BUILD}`, texPath],
      { cwd: BUILD, stdio: "ignore" }
    );
  } catch (e) {
    console.warn(`  [warn] pdflatex reported errors for ${base} (continuing)`);
  }

  if (!fs.existsSync(pdfPath)) {
    console.error(`  [fail] ${base}: PDF not produced`);
    return;
  }

  // rasterize with the existing converter
  try {
    execFileSync("node", [path.join(ROOT, "scripts", "pdf2png.mjs"), pdfPath, "--force"], {
      cwd: ROOT,
      stdio: "ignore",
    });
  } catch (e) {
    console.error(`  [fail] ${base}: png conversion error`);
    return;
  }

  const builtPng = pdfPath.replace(/\.pdf$/i, ".png");
  if (fs.existsSync(builtPng)) {
    fs.copyFileSync(builtPng, pngPath);
    console.log(
      `  table${n}.png  (${path.basename(pngPath)}, ${(fs.statSync(pngPath).size / 1024).toFixed(0)} KB)`
    );
    manifest.push({
      src: `/figures/tables/table${n}.png`,
      caption: t.caption || `Table ${n}`,
    });
  }
});

// write a data module so App.jsx stays in sync
const dataModule = `// AUTO-GENERATED by scripts/build-tables.mjs — do not edit by hand.
export const TABLES = ${JSON.stringify(manifest, null, 2)};
`;
fs.writeFileSync(path.join(ROOT, "src", "tables-data.js"), dataModule);
console.log(`\nDone. ${manifest.length} table image(s) -> public/figures/tables/`);
