// AUTO-GENERATED by scripts/build-tables.mjs — do not edit by hand.
export const TABLES = [
  {
    "src": "/figures/tables/table1.png",
    "caption": "Representative indoor scene datasets and their supported scene understanding capabilities."
  },
  {
    "src": "/figures/tables/table2.png",
    "caption": "<b>Evaluation metrics for actionable indoor scene understanding.</b> Metrics are organized along the four capability layers of this survey, covering rendering and geometric quality, semantic and relational accuracy, physical plausibility, and task-level success."
  },
  {
    "src": "/figures/tables/table4.png",
    "caption": "Core perspectives and representative advances in physical and functional understanding of indoor scenes."
  },
  {
    "src": "/figures/tables/table5.png",
    "caption": "Taxonomy of Embodied Intelligence: From Visual Understanding to Executable Actions"
  }
];
